import GetQuestions from "./GetQuestionsB";

export const metadata = {
  title: "Chestionare Categoria B - SalaDinPrima.ro",
  description: "Generated by create next app",
  keywords: "Generated by create next app",
};

export default function ChestionareDrpciv() {
    return (
      <main>
        <GetQuestions/>
      </main>
    );
  }
  